# Generated by Django 4.1.5 on 2025-08-26 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_product_discount_alter_product_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variation',
            name='variation_category',
            field=models.CharField(choices=[('color', 'color'), ('storage', 'storage'), ('size', 'size')], max_length=100),
        ),
    ]
